/**
 * ---------------------------------------------------
 * 👷 Generated by figma2tailwind. Do not modify !
 * Change assets/design-tokens/tokens.json instead.
 * ---------------------------------------------------
 * */

export default {
  ".type-display-1": {
    "font-size": "64px",
    "font-family": "Inter",
    "font-weight": "800",
    "font-style": "normal",
    "line-height": "64px",
    "letter-spacing": "0.41px",
    "text-decoration": "none",
    "text-transform": "none"
  },
  ".type-display-2": {
    "font-size": "56px",
    "font-family": "Inter",
    "font-weight": "800",
    "font-style": "normal",
    "line-height": "64px",
    "letter-spacing": "-0.3px",
    "text-decoration": "none",
    "text-transform": "none"
  },
  ".type-display-3": {
    "font-size": "48px",
    "font-family": "Inter",
    "font-weight": "800",
    "font-style": "normal",
    "line-height": "56px",
    "letter-spacing": "-0.3px",
    "text-decoration": "none",
    "text-transform": "none"
  },
  ".type-heading-1": {
    "font-size": "32px",
    "font-family": "Inter",
    "font-weight": "800",
    "font-style": "normal",
    "line-height": "40px",
    "letter-spacing": "0.41px",
    "text-decoration": "none",
    "text-transform": "none"
  },
  ".type-heading-2": {
    "font-size": "28px",
    "font-family": "Inter",
    "font-weight": "800",
    "font-style": "normal",
    "line-height": "32px",
    "letter-spacing": "-0.3px",
    "text-decoration": "none",
    "text-transform": "none"
  },
  ".type-heading-3": {
    "font-size": "24px",
    "font-family": "Inter",
    "font-weight": "800",
    "font-style": "normal",
    "line-height": "32px",
    "letter-spacing": "-0.3px",
    "text-decoration": "none",
    "text-transform": "none"
  },
  ".type-title-1": {
    "font-size": "18px",
    "font-family": "Inter",
    "font-weight": "600",
    "font-style": "normal",
    "line-height": "24px",
    "letter-spacing": "normal",
    "text-decoration": "none",
    "text-transform": "none"
  },
  ".type-title-2": {
    "font-size": "16px",
    "font-family": "Inter",
    "font-weight": "600",
    "font-style": "normal",
    "line-height": "20px",
    "letter-spacing": "normal",
    "text-decoration": "none",
    "text-transform": "none"
  },
  ".type-title-3": {
    "font-size": "14px",
    "font-family": "Inter",
    "font-weight": "600",
    "font-style": "normal",
    "line-height": "20px",
    "letter-spacing": "normal",
    "text-decoration": "none",
    "text-transform": "none"
  },
  ".type-subtitle-1": {
    "font-size": "17px",
    "font-family": "Inter",
    "font-weight": "500",
    "font-style": "normal",
    "line-height": "24px",
    "letter-spacing": "-0.3px",
    "text-decoration": "none",
    "text-transform": "none"
  },
  ".type-subtitle-2": {
    "font-size": "15px",
    "font-family": "Inter",
    "font-weight": "500",
    "font-style": "normal",
    "line-height": "20px",
    "letter-spacing": "-0.3px",
    "text-decoration": "none",
    "text-transform": "none"
  },
  ".type-subtitle-3": {
    "font-size": "13px",
    "font-family": "Inter",
    "font-weight": "500",
    "font-style": "normal",
    "line-height": "20px",
    "letter-spacing": "-0.3px",
    "text-decoration": "none",
    "text-transform": "none"
  },
  ".type-paragraph-1": {
    "font-size": "17px",
    "font-family": "Inter",
    "font-weight": "500",
    "font-style": "normal",
    "line-height": "28px",
    "letter-spacing": "-0.3px",
    "text-decoration": "none",
    "text-transform": "none"
  },
  ".type-paragraph-2": {
    "font-size": "15px",
    "font-family": "Inter",
    "font-weight": "500",
    "font-style": "normal",
    "line-height": "24px",
    "letter-spacing": "-0.3px",
    "text-decoration": "none",
    "text-transform": "none"
  },
  ".type-paragraph-3": {
    "font-size": "13px",
    "font-family": "Inter",
    "font-weight": "500",
    "font-style": "normal",
    "line-height": "24px",
    "letter-spacing": "-0.3px",
    "text-decoration": "none",
    "text-transform": "none"
  }
}
