/**
 * ---------------------------------------------------
 * 👷 Generated by figma2tailwind. Do not modify !
 * Change assets/design-tokens/tokens.json instead.
 * ---------------------------------------------------
 * */

export default {
  "tint": "var(--bmm-tint)",
  "label": {
    "1": "var(--bmm-label-1)",
    "2": "var(--bmm-label-2)",
    "3": "var(--bmm-label-3)",
    "4": "var(--bmm-label-4)",
    "separator": "var(--bmm-label-separator)"
  },
  "background": {
    "1": "var(--bmm-background-1)",
    "2": "var(--bmm-background-2)",
    "3": "var(--bmm-background-3)",
    "4": "var(--bmm-background-4)",
    "toolbar": "var(--bmm-background-toolbar)"
  },
  "on-color": {
    "1": "var(--bmm-on-color-1)",
    "2": "var(--bmm-on-color-2)",
    "3": "var(--bmm-on-color-3)",
    "4": "var(--bmm-on-color-4)"
  },
  "utility": {
    "radio": "var(--bmm-utility-radio)",
    "notification": "var(--bmm-utility-notification)",
    "auto": "var(--bmm-utility-auto)"
  },
  "white": {
    "1": "var(--bmm-white-1)",
    "2": "var(--bmm-white-2)",
    "3": "var(--bmm-white-3)",
    "4": "var(--bmm-white-4)",
    "separator": "var(--bmm-white-separator)"
  },
  "black": {
    "1": "var(--bmm-black-1)",
    "2": "var(--bmm-black-2)",
    "3": "var(--bmm-black-3)",
    "4": "var(--bmm-black-4)",
    "separator": "var(--bmm-black-separator)"
  }
}
