// @ts-nocheck - This script should fail if anything is wrong and someone needs to have a look at it manually anyways.

import { promises as fs } from "fs";
import generateColors from "./colors";
import generateTypography from "./typography";

const shouldNotHaveSuffix = (theme) => ["light", "global"].includes(theme);

async function writeTailwindColors(tailwindColors: Record<string, any>) {
  await fs.writeFile(
    "./assets/design-tokens/tailwind-colors.generated.ts",
    `/**
 * ---------------------------------------------------
 * 👷 Generated by figma2tailwind. Do not modify !
 * ---------------------------------------------------
 * */

export default ${JSON.stringify(tailwindColors, null, 2)}
`,
    "utf8",
  );
}

async function writeTailwindTypography(
  tailwindTypography: Record<string, any>,
) {
  await fs.writeFile(
    "./assets/design-tokens/tailwind-typography.generated.ts",
    `/**
 * ---------------------------------------------------
 * 👷 Generated by figma2tailwind. Do not modify !
 * ---------------------------------------------------
 * */

export default ${JSON.stringify(tailwindTypography, null, 2)}
`,
    "utf8",
  );
}

async function writeColorsCss(content: string) {
  await fs.writeFile(
    "./assets/design-tokens/colors.generated.css",
    content,
    "utf8",
  );
}

async function writeColors(figmaInput) {
  const { color } = figmaInput;
  const transformedColors = {};

  Object.entries(color).forEach(([theme, themeValue]) => {
    Object.entries(themeValue).forEach(([colorKey, colorValue]) => {
      const suffixedKey = shouldNotHaveSuffix(theme)
        ? colorKey
        : `${colorKey}-${theme}`;

      if (!colorValue.value) {
        transformedColors[suffixedKey] ||= {};

        Object.entries(colorValue).forEach(
          ([innerColorWeight, innerColorValue]) => {
            transformedColors[suffixedKey][innerColorWeight] =
              innerColorValue.value;
          },
        );
      } else {
        transformedColors[suffixedKey] = colorValue.value;
      }
    });
  });

  // Simplifies class names so bg-info-default becomes bg-info
  const colors = JSON.parse(
    JSON.stringify(transformedColors).replaceAll("default", "DEFAULT"),
  );

  const { cssString, tailwindColors } = generateColors(colors);
  await writeColorsCss(cssString);
  await writeTailwindColors(tailwindColors);

  const typography = generateTypography(figmaInput.typography);
  await writeTailwindTypography(typography);
}

async function getFigmaInput() {
  const content = await fs.readFile(
    "./assets/design-tokens/tokens.json",
    "utf-8",
  );
  return JSON.parse(content);
}

export default async function main() {
  const figmaInput = await getFigmaInput();
  await writeColors(figmaInput);
}
